name: justice_mango
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.0+2305313

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  hive: ^2.2.3
  flutter_cache_manager: ^3.3.0
  hive_flutter: ^1.1.0
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  beautiful_soup_dart: ^0.3.0
  shared_preferences: ^2.1.1

  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.5
  flutter_speed_dial: ^7.0.0
  flutter_focus_watcher: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre

  random_string: ^2.3.1
  string_to_hex: ^0.2.2
  cupertino_icons: ^1.0.5
  jdenticon_dart: ^2.0.0
  flutter_svg: ^2.0.6
  equatable: ^2.0.5
  photo_view: ^0.14.0
  salomon_bottom_bar: ^3.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  json_serializable:
  flutter_launcher_icons: ^0.13.1
  # flutter_app_name: ^0.1.1
  flutter_native_splash: ^2.3.0
  very_good_analysis: ^5.0.0+1
  flutter_lints: ^2.0.1

dependency_overrides:
  http: ^1.0.0

flutter_app_name:
  name: "Fluffy"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/shanshan-modified.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/shanshan-modified.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/shanshan-modified.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/data/
    - assets/icons/
    - assets/images/
#  fonts:
#    - family: WorkSans
#      fonts:
#        - asset: assets/fonts/WorkSans-Regular.ttf
#        - asset: assets/fonts/WorkSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/WorkSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/WorkSans-Bold.ttf
#          weight: 700
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Bold.ttf
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Medium.ttf
#          weight: 400
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
